--
-- Seeder untuk mengisi tabel `soal_papikostik` dengan 90 soal standar.
-- Jalankan query ini di database Anda (misal: melalui phpMyAdmin) untuk mengisi soal secara otomatis.
--
INSERT INTO `soal_papikostik` (`nomor_soal`, `pernyataan_a`, `aspek_a`, `pernyataan_b`, `aspek_b`) VALUES
(1, 'Saya seorang pekerja keras', 'G', 'Saya bukan seorang pemurung', 'E'),
(2, 'Saya suka bekerja lebih baik dari orang lain', 'A', 'Saya suka mengerjakan apa yang sedang saya kerjakan, sampai selesai', 'N'),
(3, 'Saya suka memberi petunjuk kepada orang lain dalam bekerja', 'P', 'Saya suka memuji orang yang pekerjaannya baik', 'O'),
(4, 'Saya suka mencoba hal-hal baru', 'T', 'Saya suka menceritakan keberhasilan saya dalam bekerja', 'X'),
(5, 'Saya suka menyenangkan hati pimpinan saya', 'F', 'Saya suka menjadi bagian dari kelompok', 'B'),
(6, 'Saya seorang yang bersemangat', 'V', 'Saya seorang yang cepat dalam mengambil keputusan', 'I'),
(7, 'Saya suka diperhatikan oleh kelompok saya', 'X', 'Saya suka bersahabat karib dengan teman-teman saya', 'S'),
(8, 'Saya suka memikirkan suatu persoalan secara mendalam', 'R', 'Saya suka bekerja dengan hal-hal yang bersifat rinci', 'D'),
(9, 'Saya suka mengatur pekerjaan saya secara rapi', 'C', 'Saya seorang yang tidak mudah marah', 'E'),
(10, 'Saya bukan seorang yang cepat gugup', 'E', 'Saya suka menyelesaikan suatu pekerjaan', 'N'),
(11, 'Saya suka diperlakukan secara adil', 'F', 'Saya suka menunjukkan rasa simpati saya kepada kawan-kawan saya', 'O'),
(12, 'Saya suka mengerjakan pekerjaan-pekerjaan yang sulit', 'A', 'Saya suka memimpin suatu rapat', 'P'),
(13, 'Saya suka melakukan pekerjaan bersama dengan teman-teman daripada bekerja sendiri', 'B', 'Saya suka mencoba hal-hal baru', 'T'),
(14, 'Saya suka berada di lingkungan yang penuh semangat', 'V', 'Saya suka bersahabat karib dengan teman-teman saya', 'S'),
(15, 'Saya suka menjadi pusat perhatian', 'X', 'Saya suka berpikir tentang suatu gagasan', 'R'),
(16, 'Saya suka bekerja dengan hal-hal yang menuntut ketelitian', 'D', 'Saya suka merencanakan pekerjaan saya', 'C'),
(17, 'Saya suka memberitahu orang lain bagaimana cara melakukan sesuatu', 'P', 'Saya suka menyelesaikan satu pekerjaan sebelum memulai pekerjaan lain', 'N'),
(18, 'Saya seorang yang periang', 'E', 'Saya suka menyenangkan hati pimpinan saya', 'F'),
(19, 'Saya suka mengikuti perintah-perintah yang diberikan kepada saya', 'W', 'Saya suka menunjukkan rasa simpati saya kepada orang lain', 'O'),
(20, 'Saya suka bekerja keras', 'G', 'Saya suka memimpin suatu kelompok', 'I'),
(21, 'Saya suka berada di tengah-tengah orang banyak', 'S', 'Saya suka memikirkan suatu masalah secara mendalam', 'R'),
(22, 'Saya suka mencoba hal-hal baru', 'T', 'Saya suka bekerja dengan hal-hal yang bersifat rinci', 'D'),
(23, 'Saya suka merencanakan dan mengatur', 'C', 'Saya suka menyelesaikan suatu pekerjaan atau tugas', 'N'),
(24, 'Saya suka diperhatikan oleh orang lain', 'X', 'Saya suka mengikuti aturan-aturan yang ada', 'W'),
(25, 'Saya berusaha untuk sangat ramah dengan orang-orang', 'S', 'Saya seorang yang tidak mudah tersinggung', 'E'),
(26, 'Saya suka memberitahu kelompok apa yang harus dilakukan', 'P', 'Saya suka bekerja keras', 'G'),
(27, 'Saya suka melakukan hal-hal yang baru dan berbeda', 'T', 'Saya suka memberitahukan kepada orang lain bila mereka melakukan pekerjaan dengan baik', 'O'),
(28, 'Saya suka mempunyai teman-teman yang akrab', 'B', 'Saya suka bersaing dengan orang lain', 'A'),
(29, 'Saya suka memimpin suatu kelompok', 'I', 'Saya suka memikirkan suatu persoalan', 'R'),
(30, 'Saya suka pekerjaan yang menuntut ketelitian', 'D', 'Saya seorang yang bersemangat tinggi', 'V'),
(31, 'Saya suka merencanakan pekerjaan saya', 'C', 'Saya suka mengikuti petunjuk-petunjuk dari atasan saya', 'F'),
(32, 'Saya suka menyelesaikan pekerjaan yang sudah saya mulai', 'N', 'Saya suka berteman baik dengan atasan saya', 'W'),
(33, 'Saya tidak lekas marah', 'E', 'Saya suka berdebat', 'K'),
(34, 'Saya suka bekerja lebih baik dari orang lain', 'A', 'Saya suka bergaul dengan orang banyak', 'S'),
(35, 'Saya suka berada dalam kelompok', 'B', 'Saya suka memimpin dalam kelompok', 'P'),
(36, 'Saya suka memikirkan sesuatu sampai tuntas', 'R', 'Saya suka mencoba hal-hal yang baru dan berbeda', 'T'),
(37, 'Saya suka bekerja dengan bersemangat', 'V', 'Saya suka pekerjaan yang rapi dan teratur', 'C'),
(38, 'Saya suka membuat orang lain melakukan apa yang saya inginkan', 'P', 'Saya suka menjadi pusat perhatian', 'X'),
(39, 'Saya suka mengikuti perintah pimpinan', 'F', 'Saya suka bekerja keras', 'G'),
(40, 'Saya suka menyelesaikan pekerjaan yang ada di tangan saya', 'N', 'Saya suka menjadi seorang yang penuh gagasan', 'I'),
(41, 'Saya suka menolong orang lain', 'O', 'Saya tidak mudah tersinggung', 'E'),
(42, 'Saya suka berdebat', 'K', 'Saya suka berada di antara orang banyak', 'S'),
(43, 'Saya suka bersaing dengan orang lain', 'A', 'Saya suka berteman akrab', 'B'),
(44, 'Saya seorang yang berpikir mendalam', 'R', 'Saya seorang yang bersemangat', 'V'),
(45, 'Saya suka pekerjaan yang terperinci', 'D', 'Saya suka memimpin suatu kelompok', 'P'),
(46, 'Saya suka pekerjaan yang teratur dan rapi', 'C', 'Saya suka menjadi pusat perhatian', 'X'),
(47, 'Saya suka bekerja di bawah pengawasan', 'W', 'Saya suka bekerja keras', 'G'),
(48, 'Saya seorang yang cepat mengambil keputusan', 'I', 'Saya suka menyelesaikan pekerjaan sampai tuntas', 'N'),
(49, 'Saya suka menyenangkan hati orang yang berkuasa', 'F', 'Saya suka berdebat', 'K'),
(50, 'Saya suka menolong teman-teman saya', 'O', 'Saya suka bergaul dengan orang lain', 'S'),
(51, 'Saya suka menjadi anggota suatu kelompok', 'B', 'Saya suka memikirkan suatu masalah', 'R'),
(52, 'Saya suka bekerja giat', 'V', 'Saya suka bersaing dengan orang lain', 'A'),
(53, 'Saya suka pekerjaan yang memerlukan ketelitian', 'D', 'Saya suka menjadi pusat perhatian', 'X'),
(54, 'Saya suka merencanakan pekerjaan saya', 'C', 'Saya seorang yang cepat mengambil keputusan', 'I'),
(55, 'Saya suka bekerja untuk seorang pimpinan', 'W', 'Saya suka memberitahu orang lain apa yang harus dilakukan', 'P'),
(56, 'Saya suka menyelesaikan tugas saya', 'N', 'Saya suka berdebat', 'K'),
(57, 'Saya tidak mudah marah', 'E', 'Saya suka bekerja lebih cepat dari orang lain', 'A'),
(58, 'Saya suka berteman dengan banyak orang', 'S', 'Saya suka bekerja keras', 'G'),
(59, 'Saya suka melakukan hal-hal yang baru', 'T', 'Saya suka mengikuti pimpinan saya', 'F'),
(60, 'Saya suka mempunyai teman-teman yang akrab', 'B', 'Saya suka memimpin suatu kelompok', 'I'),
(61, 'Saya suka berpikir', 'R', 'Saya suka berdebat', 'K'),
(62, 'Saya suka bekerja dengan cepat', 'V', 'Saya suka mengatur pekerjaan saya', 'C'),
(63, 'Saya suka diperhatikan orang lain', 'X', 'Saya suka bekerja di bawah perintah', 'W'),
(64, 'Saya suka memberitahu orang lain apa yang harus dikerjakan', 'P', 'Saya cepat mengambil keputusan', 'I'),
(65, 'Saya suka menyelesaikan pekerjaan saya', 'N', 'Saya suka menyenangkan hati pimpinan saya', 'F'),
(66, 'Saya suka dipuji orang', 'O', 'Saya suka bekerja lebih baik dari orang lain', 'A'),
(67, 'Saya suka bergaul dengan orang lain', 'S', 'Saya suka melakukan sesuatu hal yang baru', 'T'),
(68, 'Saya suka berada dalam suatu kelompok', 'B', 'Saya suka berdebat', 'K'),
(69, 'Saya suka bekerja giat', 'V', 'Saya cepat mengambil keputusan', 'I'),
(70, 'Saya suka memikirkan suatu persoalan', 'R', 'Saya suka merencanakan pekerjaan saya', 'C'),
(71, 'Saya suka bekerja dengan hal-hal yang bersifat rinci', 'D', 'Saya suka bekerja di bawah perintah', 'W'),
(72, 'Saya suka mengatur orang lain', 'P', 'Saya suka berdebat', 'K'),
(73, 'Saya seorang yang tenang', 'E', 'Saya suka bekerja di bawah pengawasan pimpinan', 'F'),
(74, 'Saya suka menyelesaikan tugas-tugas saya', 'N', 'Saya suka dipuji karena hasil kerja saya', 'O'),
(75, 'Saya suka bekerja keras', 'G', 'Saya suka mencoba hal-hal baru', 'T'),
(76, 'Saya suka berteman akrab', 'B', 'Saya suka mengambil keputusan', 'I'),
(77, 'Saya suka berdebat', 'K', 'Saya suka pekerjaan yang memerlukan ketelitian', 'D'),
(78, 'Saya suka bekerja dengan penuh semangat', 'V', 'Saya suka diperhatikan oleh orang lain', 'X'),
(79, 'Saya suka merencanakan pekerjaan saya', 'C', 'Saya suka mengikuti atasan saya', 'W'),
(80, 'Saya suka mengatur orang lain', 'P', 'Saya suka bekerja lebih baik dari orang lain', 'A'),
(81, 'Saya suka menyelesaikan setiap pekerjaan yang saya mulai', 'N', 'Saya suka bergaul dengan orang lain', 'S'),
(82, 'Saya suka menyenangkan hati pimpinan', 'F', 'Saya cepat mengambil keputusan', 'I'),
(83, 'Saya suka memberitahu orang lain jika mereka berbuat salah', 'K', 'Saya suka menolong orang lain', 'O'),
(84, 'Saya suka melakukan pekerjaan lebih baik dari orang lain', 'A', 'Saya suka mencoba hal-hal yang baru', 'T'),
(85, 'Saya suka menjadi anggota suatu kelompok', 'B', 'Saya suka bekerja dengan penuh semangat', 'V'),
(86, 'Saya suka memikirkan suatu persoalan', 'R', 'Saya suka bekerja di bawah perintah', 'W'),
(87, 'Saya suka bekerja dengan hal-hal yang terperinci', 'D', 'Saya suka mengatur orang lain', 'P'),
(88, 'Saya suka merencanakan pekerjaan saya', 'C', 'Saya suka berdebat', 'K'),
(89, 'Saya adalah seorang pemimpin yang baik', 'I', 'Saya adalah seorang yang tenang', 'E'),
(90, 'Saya suka bekerja keras', 'G', 'Saya suka berteman akrab', 'B');
COMMIT;
